spring:
  mail:
    host: "smtp.qq.com"
    port: 465
    username: "173293955@qq.com"
    password: "ztiskyfqaqzscagf"
    properties:
      mail.smtp.ssl.enable: true

scheduled:
  trigger:
    enabled: true
    cron: "*/1 * * * * ?"

platform:
  android:
    imoutai:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.moutai.mall"
        appActivity: "com.moutai.mall.module.splash.SplashActivity"
    taobao:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.taobao.taobao"
        appActivity: "com.taobao.tao.welcome.Welcome"
    jd:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.jingdong.app.mall"
        appActivity: ".main.MainActivity"
    suning:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.suning.mobile.ebuy"
        appActivity: ".commodity.CommodityMainActivity"
    yijiu:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.yijiuyijiu.eshop"
        appActivity: "com.b2c1919.app.ui.launch.LaunchActivity"
    siku:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.secoo"
        appActivity: "com.secoo.app.mvp.ui.activity.LauncherActivity"
    yanxuan:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.netease.yanxuan"
        appActivity: ".module.mainpage.activity.MainPageActivity"
    xiaomi:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.xiaomi.youpin"
        appActivity: "com.xiaomi.youpin.activity.SplashActivity"
    zhenkuaile:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.gome.eshopnew"
        appActivity: "com.gome.ecmall.home.LaunchActivity"
