spring:
  mail:
    host: "smtp.qq.com"
    port: 465
    username: "173293955@qq.com"
    password: "ztiskyfqaqzscagf"
    properties:
      mail.smtp.ssl.enable: true

scheduled:
  trigger:
    enabled: true
    cron: "*/1 * * * * ?"

platform:
  android:
    imoutai:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.moutai.mall"
        appActivity: "com.moutai.mall.module.splash.SplashActivity"
    taobao:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.taobao.taobao"
        appActivity: "com.taobao.tao.welcome.Welcome"
    jd:
      scheduled:
        enabled: true
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.jingdong.app.mall"
        appActivity: ".main.MainActivity"
    suning:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.suning.mobile.ebuy"
        appActivity: ".commodity.CommodityMainActivity"
    yijiuyijiu:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.yijiuyijiu.eshop"
        appActivity: "com.b2c1919.app.ui.product.ProductDetailActivity"
    siku:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.secoo"
        appActivity: ".gooddetails.mvp.ui.activity.GoodDetailsActivity"
    wangyi:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.netease.yanxuan"
        appActivity: ".module.goods.activity.GoodsDetailActivity"
    xiaomi:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.xiaomi.youpin"
        appActivity: "com.xiaomi.miot.store.ui.MiotStoreMainActivity"
    zhenkuaile:
      scheduled:
      connect:
        udid: "8e156534"
        unlockType: "password"
        unlockKey: "9527"
        noReset: "true"
        appPackage: "com.gome.eshopnew"
        appActivity: "com.gome.ecmall.product.ui.GProductDetailActivity"
