spring:
  mail:
    host: "smtp.qq.com"
    port: 465
    username: "173293955@qq.com"
    password: "ztiskyfqaqzscagf"
    properties:
      mail.smtp.ssl.enable: true

scheduled:
  reserve:
    enabled: true
    cron:
      one: "0 35 10 * * *"  #每天10:35
      two: "0 40 19 * * *" #每天17:40

platform:
  android:
    imoutai:
      scheduled:
        enabled: false
        cron: "*/1 * * * * ?"
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.moutai.mall"
        appActivity: "com.moutai.mall.module.splash.SplashActivity"
    taobao:
      scheduled:
        enabled: true
        cron:
          seckill: "35 59 19 * * *" #每天20:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.taobao.taobao"
        appActivity: "com.taobao.tao.welcome.Welcome"
    jd:
      scheduled:
        enabled: true
        cron:
          seckill: "35 59 11 ? * 1-5" #工作日12:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.jingdong.app.mall"
        appActivity: ".main.MainActivity"
    suning:
      scheduled:
        enabled: true
        cron:
          seckill: "35 29 0 ? * 1-5" #工作日9:30
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.suning.mobile.ebuy"
        appActivity: "com.suning.mobile.ebuy.host.InitialActivity"
    yijiu:
      scheduled:
        enabled: true
        cron:
          seckill:
            one: "35 59 9 * * *" #每天10:00
            two: "35 59 16 * * *" #每天17:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.yijiuyijiu.eshop"
        appActivity: "com.b2c1919.app.ui.launch.LaunchActivity"
    siku:
      scheduled:
        enabled: false
        cron:
          seckill: "35 59 9 * * *" #每天10:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.secoo"
        appActivity: "com.secoo.app.mvp.ui.activity.LauncherActivity"
    yanxuan:
      scheduled:
        enabled: true
        cron:
          seckill:
            one: "35 59 10 * * *" #每天11:00
            two: "35 59 21 * * *" #每天22:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.netease.yanxuan"
        appActivity: ".module.mainpage.activity.MainPageActivity"
    xiaomi:
      scheduled:
        enabled: false
        cron:
          seckill: "35 59 9 * * *" #每天10:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.xiaomi.youpin"
        appActivity: "com.xiaomi.youpin.activity.SplashActivity"
    zhenkuaile:
      scheduled:
        enabled: false
        cron: "35 59 19 * * *" #每天20:00
      connect:
        udid: "8e156534"
        unlockType: "pattern"
        unlockKey: "9527"
        uiautomator2ServerReadTimeout: "10000"
        noReset: "true"
        appPackage: "com.gome.eshopnew"
        appActivity: "com.gome.ecmall.home.LaunchActivity"
